### ISSUE TITLE
'add new service' search overlay

### ISSUE THREAD

**Issue by LucSmeets** [Sjoerdjanssenen/Subby-issues#34]
- Add a new service
- Go to 'Add new service detail view'
- Cancel
![img_0035](https://cloud.githubusercontent.com/assets/16607591/13251393/3bdbc4dc-da30-11e5-82a6-12913cde9f09.jpg)

- when you scroll:
![img_0036](https://cloud.githubusercontent.com/assets/16607591/13251410/5c851170-da30-11e5-8573-32286b5e5919.jpg)

**Comment by Sjoerdjanssenen** [comment]
Fixed.

**Comment by LucSmeets** [comment]
Still happening, only different now:

![img_0038](https://cloud.githubusercontent.com/assets/16607591/13670509/affa84d8-e6ca-11e5-86a6-bc28c1701c6b.jpg)

**Comment by Sjoerdjanssenen** [comment]
Fixed.
